import { expect, it, vi } from "vitest";
import { commandPaths, createProgram } from "../../src/program.js";

// Approved public surface. This literal is intentionally independent of the declarations.
const expected = [
  "account capacity",
  "account configure",
  "account grant list",
  "account grant revoke",
  "account passkey delete",
  "account passkey list",
  "account password",
  "account settings",
  "account two-factor disable",
  "account two-factor enable",
  "account view",
  "archive create",
  "archive download",
  "archive extract",
  "archive list",
  "auth login",
  "auth logout",
  "auth status",
  "auth switch",
  "cat",
  "cp",
  "diagnostics",
  "edit",
  "job cancel",
  "job create",
  "job list",
  "job select",
  "job view",
  "link create",
  "link list",
  "link revoke",
  "ls",
  "metadata remove",
  "metadata schema",
  "metadata set",
  "metadata view",
  "mkdir",
  "mv",
  "profile add",
  "profile list",
  "profile remove",
  "profile use",
  "restore",
  "rm",
  "search",
  "server info",
  "share create",
  "share list",
  "share open",
  "share revoke",
  "share update",
  "share view",
  "stat",
  "tag add",
  "tag remove",
  "tag rename",
  "touch",
  "transfer cancel",
  "transfer forget",
  "transfer list",
  "transfer resume",
  "transfer retry",
  "trash empty",
  "unlock",
  "url",
  "version delete",
  "version list",
  "version promote",
  "watch",
  "webdav create",
  "webdav list",
  "webdav revoke",
  "webdav update",
  "webdav view",
  "write",
] as const;

const retired = [
  "account avatar",
  "account oauth consent",
  "account oauth view",
  "account passkey begin",
  "account passkey finish",
  "account rename",
  "account search",
  "account two-factor setup",
  "account user",
  "archive url",
  "auth activate",
  "auth browser",
  "auth captcha",
  "auth config",
  "auth oauth exchange",
  "auth oauth userinfo",
  "auth passkey begin",
  "auth passkey finish",
  "auth prepare",
  "auth register",
  "auth reset-confirm",
  "auth reset-password",
  "backup configure",
  "backup history",
  "backup ignore",
  "backup list",
  "backup remove",
  "backup retry",
  "backup run",
  "backup unignore",
  "backup watch",
  "icon remove",
  "icon set",
  "link download",
  "metadata typed-remove",
  "metadata typed-set",
  "music favorite add",
  "music favorite list",
  "music favorite remove",
  "music library",
  "music playlist add",
  "music playlist create",
  "music playlist delete",
  "music playlist export",
  "music playlist list",
  "music playlist move",
  "music playlist play",
  "music playlist remove",
  "offline add",
  "offline clear",
  "offline export",
  "offline list",
  "offline remove",
  "pin add",
  "pin list",
  "pin remove",
  "share public",
  "share resolve",
  "share revoke-many",
  "view get",
  "view reset",
  "view set",
  "viewer list",
  "viewer session",
] as const;

it("exposes exactly the declared 75 command paths", () => {
  expect(commandPaths().sort()).toEqual([...expected]);
});

it("rejects every retired command before credential/backend composition", async () => {
  const compose = vi.fn(() => {
    throw new Error("Credential/backend composition must not run");
  });

  for (const command of retired) {
    for (const operands of [[], ["sample"]]) {
      await expect(
        createProgram(compose).parseAsync([...command.split(" "), ...operands], { from: "user" }),
        command,
      ).rejects.toThrow("unknown command");
    }
  }

  expect(compose).not.toHaveBeenCalled();
});
